name = "MiniNN"
uuid = "f402742a-88d0-4ef2-9d6b-a91dabed814a"
authors = ["Jack Smith <jacksmith2000@me.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"
